dist: trusty
sudo: required

language: generic

env:
 - ZSH_VERSION=5.3.1 URL=https://downloads.sourceforge.net/project/zsh/zsh/5.3.1/zsh-5.3.1.tar.xz
 - ZSH_VERSION=5.2 URL=https://downloads.sourceforge.net/project/zsh/zsh/5.2/zsh-5.2.tar.xz
 - ZSH_VERSION=5.1.1 URL=https://downloads.sourceforge.net/project/zsh/zsh/5.1.1/zsh-5.1.1.tar.xz
 - ZSH_VERSION=5.1 URL=https://downloads.sourceforge.net/project/zsh/zsh/5.1/zsh-5.1.tar.xz
 - ZSH_VERSION=5.0.8 URL=https://downloads.sourceforge.net/project/zsh/zsh/5.0.8/zsh-5.0.8.tar.gz
 - ZSH_VERSION=5.0.7 URL=https://downloads.sourceforge.net/project/zsh/zsh/5.0.7/zsh-5.0.7.tar.gz

addons:
  apt:
    packages:
    - build-essential

before_install:
    - export LOCAL="$(mktemp --directory --tmpdir=${TMPDIR:/tmp} local.bin.XXXXXX)"
    - wget $URL
    - tar -xf zsh-$ZSH_VERSION.tar.*
    - cd zsh-$ZSH_VERSION
    - ./configure --prefix=$LOCAL
    - make
    - make install
    - cd -
    - export PATH="$LOCAL/bin:$PATH"

before_script:
    - mkdir ~/bin
    - curl -L https://raw.githubusercontent.com/molovo/revolver/master/revolver > ~/bin/revolver
    - chmod u+x ~/bin/revolver
    - curl -L https://raw.githubusercontent.com/molovo/color/master/color.zsh > ~/bin/color
    - chmod u+x ~/bin/color
    - curl -L https://github.com/molovo/zunit/releases/download/v0.7.0/zunit > ~/bin/zunit
    - chmod u+x ~/bin/zunit

script:
    - zunit
